version: '3.8'

services:
  collector:
    image: logzio/otel-collector-traces:v1.0.0
    environment:
      - LOGZIO_REGION=us
      - LOGZIO_TRACES_TOKEN=FdzntCzFUFCXJEtXDMmnNUuxJMMxDBPu.
    ports:
      - "1777:1777"
      - "9411:9411"
      - "9943:9943"
      - "6831:6831"
      - "6832:6832"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "55681:55681"
      - "8888:8888"