server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: changeit
    trust-store-password: changeit
    trust-store: classpath:cacerts.jks
    protocol: TLSv1.3
  port: 8443

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/transaction-bff
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    bootstrap-servers:
      - localhost:9092

  redis:
    port: 6379
    host: localhost
    timeout: 5000
  application:
    name: transaction-bff

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://localhost:4317

springdoc:
  swagger-ui:
    path: /swagger-ui.html

limites:
  url: http://localhost:8081

transaction:
  url: http://localhost:8082

app:
  topic: transaction

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true