spring:
  config:
    import: optional:configserver:http://localhost:8888/
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}

  application:
    name: transaction-bff

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  topic: transaction