spring:
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name}
    bootstrap-servers:
      - localhost:9092

  redis:
    port: 6379
    host: localhost
    timeout: 5000
  application:
    name: transaction-bff

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://localhost:4317

springdoc:
  swagger-ui:
    path: /swagger-ui.html

limites:
  url: http://localhost:8081

transaction:
  url: http://localhost:8082

app:
  topic: transaction

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true